name: Greeting on variable day

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
          printf '%s\n' "$action_state"
        id: write

