# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Greeting on variable day later run

on:
  workflow_run:
    workflows: [Greeting on variable day]
    types:
      - completed

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: after run
        run: echo "hello"
  
