name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          FILENAME=`date  +"%y%m%d%H%M%S"`.txt
          testtype=`npm version ${{github.event.inputs.versionType}}`
          echo 123 > $FILENAME
          echo 456 > $testtype
          echo "::set-output name=$FILENAME"
          echo "::set-output name=$testtype"
        id: write

