name: Node.js Package

on:
  workflow_dispatch:
env:
  DAY_OF_WEEK: DAY_OF_WEEK_Monday # 顶层变量

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test_echo
      run: echo 'befrore'
    - name: test_if
      if: ${{ env.DAY_OF_WEEK == 'Monday' }}
      run: |
        echo " Today is $DAY_OF_WEEK!"
        echo "here is: $test_if_var"
        echo "$First_Name $MY_ENV_VAR"
      env: 
        test_if_var: I'M TEST ENV VAR
    env:
      First_Name: Mona
      MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
      
