name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test_echo
      run: echo 'befrore'
    - name: test_if
      if: ${{ 'failure' == 'failure' }}
      run: echo 'hello, ${{$env.CUSTOM_ENV_VAR}}'
    env:
      CUSTOM_ENV_VAR: 'zhaoyehogn'
      MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
