name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          FILENAME=`date  +"%y%m%d%H%M%S"`.txt
          echo 123 > $FILENAME
          echo "::set-output name=$FILENAME"
        id: write
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "add ${{ steps.write.outputs.name }}"
