# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test_echo
      run: echo 'befrore'
    - name: test_if
      if: ${{ 'n' == 'failure' }}
      run: echo 'success'
