name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          `a=${npm version patch}` >> "$GITHUB_ENV"
          echo $a
        id: write

