# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Failing step
      id: demo
      run: exit 1
    - name: The demo step has failed
      if: ${{ failure() && steps.demo.conclusion == 'failure' }}
