name: Greeting on variable day

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

